spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
    data: classpath:test.sql

  jpa:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update

          show_sql: true
